[package]
name = "desktop-agent"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "desktop-agent"
path = "src/main.rs"

[[bin]]
name = "viewer"
path = "src/bin/viewer.rs"

[dependencies]
sha2 = "0.10"
minifb = "0.25"
enigo = "0.2.1"
screenshots = "0.8"
cpal = "0.15"
lz4_flex = "0.11"
arboard = "3.3"
rand = "0.8"
image = { version = "0.24", default-features = false, features = ["png"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
windows-sys = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_UI_HiDpi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_System_Registry"
] }