[package]
name = "desktop-agent"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "desktop-agent"
path = "src/main.rs"

[[bin]]
name = "viewer"
path = "src/bin/viewer.rs"

[dependencies]
sha2 = "0.10"
minifb = "0.25"
enigo = "0.2.1"
screenshots = "0.8"
cpal = "0.15"
lz4_flex = "0.11"
arboard = "3.3"
rand = "0.8"
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
windows-sys = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_UI_HiDpi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_System_Registry",
    "Win32_System_Threading",
    "Win32_System_StationsAndDesktops",
    "Win32_Graphics_Gdi"
] }
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_Media_MediaFoundation",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Variant"
] }
openh264 = "0.9.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tungstenite = "0.20"
