[package]
name = "screenshare-setup"
version = "1.1.0"
edition = "2021"

[[bin]]
name = "screenshare-setup"
path = "src/main.rs"

[dependencies]
windows-sys = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_UI_Controls",
    "Win32_UI_Shell",
    "Win32_Graphics_Dwm",
    "Win32_System_Registry",
    "Win32_System_LibraryLoader",
    "Win32_System_ApplicationInstallationAndServicing",
] }
