[package]
name = "relay-server"
version = "1.1.1"
edition = "2021"

[[bin]]
name = "relay-server"
path = "src/main.rs"

[dependencies]
tungstenite = "0.20"
sha2 = "0.10"
ctrlc = "3.2"
[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_System_Registry"
] }
